server:
  port: ${SERVICE_PORT:9095}
  connection:
    timeout: 20000

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka-server}
    port: ${EUREKA_PORT:8761}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false

#authserver:
#  hostname: http://localhost:9092
#security:
#  oauth2:
#    resource:
#      userInfoUri: ${authserver.hostname}/user